const path = require("node:path");
const fs = require("node:fs");
const os = require("node:os");
const crypto = require("node:crypto");
const { spawn, execSync } = require("node:child_process");
const { HEARTBEAT_INTERVAL_MS, HOSTED_VOIP_SERVERS } = require("../shared/protocol");
const { setUi } = require("./ui");
const { topStrategy } = require("./brain");
const { startWebUi, writeDashboardUrl, dashboardUrlPath } = require("./webui");
const localDb = require("./local-db");
const sync = require("./sync");
const { emailQualifiedLead } = require("./email");
const { runLocalCall } = require("./local-call-controller");
const { normalizeLanguage } = require("./language");

function defaultConfigPath() { const base=process.env.AUTODIAL_HOME?process.env.AUTODIAL_HOME:path.join(os.homedir(),".magicdialer"); return path.join(base,"config.json"); }
function loadConfig(p=defaultConfigPath()){try{return JSON.parse(fs.readFileSync(p,"utf8"));}catch{return null;}}
function saveConfig(c,p=defaultConfigPath()){try{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(c,null,2),"utf8");}catch(e){log("saveConfig failed: "+(e&&e.message||e));}}
function log(m){console.log(`[agent] ${new Date().toISOString()} ${m}`);}
function isPacked(){const b=path.basename(process.execPath||"").toLowerCase();return b==="agent.exe"||b==="magicdialer.exe";}
function openBrowser(url){try{spawn("cmd.exe",["/c","start","",String(url)],{windowsHide:true,stdio:"ignore"}).unref();}catch{}}
function openDashboardExternal(){try{const t=fs.readFileSync(dashboardUrlPath(),"utf8"),m=t.match(/^URL=(.+)$/m);if(m&&m[1].trim()){openBrowser(m[1].trim());return true;}}catch{}return false;}
const WATCHDOG_LOCK=path.join(os.homedir(),"AppData","Local","Magic Dialer","watchdog.lock"),CRASH_WINDOW_MS=45000,CRASH_BEFORE_BACKOFF=3;
function pidAlive(pid){try{process.kill(pid,0);return true;}catch{return false;}}
function takeWatchdogLock(){try{if(fs.existsSync(WATCHDOG_LOCK)){const old=Number(String(fs.readFileSync(WATCHDOG_LOCK,"utf8")).trim());if(old&&(process.platform==="win32"?old!==process.pid&&pidAlive(old):pidAlive(old))){console.log(`[watchdog] another supervisor (pid ${old}) is already running — exiting.`);return false;}}fs.mkdirSync(path.dirname(WATCHDOG_LOCK),{recursive:true});fs.writeFileSync(WATCHDOG_LOCK,String(process.pid));return true;}catch{return true;}}
async function runWatchdog(args){if(!takeWatchdogLock())return;const childArgs=args.filter(a=>a!=="--watchdog");childArgs.push("--no-browser");const childCmd=process.env.MD_WATCHDOG_CHILD?{cmd:"cmd.exe",args:["/d","/c",process.env.MD_WATCHDOG_CHILD]}:{cmd:process.execPath,args:childArgs};let crashes=0,lastExit=0;const restart=n=>new Promise(r=>setTimeout(r,n));while(true){log(`watchdog starting agent (pid engine: ${childCmd.cmd})...`);const child=spawn(childCmd.cmd,childCmd.args,{stdio:["ignore","inherit","inherit"]});const exited=await new Promise(resolve=>{child.on("exit",code=>resolve({code,ranFor:Date.now()-(child._start||Date.now())}));child._start=Date.now();});const cfgDir=path.join(os.homedir(),"AppData","Local","Magic Dialer");let disabled=false;try{const st=JSON.parse(fs.readFileSync(path.join(cfgDir,"status.json"),"utf8"));disabled=st&&st.status==="DISABLED";}catch{}if(disabled){log("agent left status DISABLED — supervisor standing down.");return;}const wasCrash=exited.code!==0||exited.ranFor<CRASH_WINDOW_MS,crashy=wasCrash&&Date.now()-lastExit<CRASH_WINDOW_MS;crashes=(wasCrash&&crashy)?Math.min(crashes+1,10):(wasCrash?1:0);lastExit=Date.now();if(wasCrash&&crashes>=CRASH_BEFORE_BACKOFF){const backoff=Math.min(1000*crashes,300000);log(`agent exited ${exited.code} after ${exited.ranFor}ms — crash streak ${crashes}, backing off ${backoff}ms.`);await restart(backoff);}else if(exited.ranFor>=CRASH_WINDOW_MS){log(`agent exited cleanly (code ${exited.code}) after ${exited.ranFor}ms — restarting in 4s.`);await restart(4000);}else{crashes=wasCrash&&crashy?crashes+1:Math.max(0,crashes-1);log(`agent exited early (code ${exited.code}) — restarting in ${wasCrash?4000:2000}ms.`);await restart(wasCrash?4000:2000);}}}
const VERSION="2.0.0-local-media";
function applyPortalConfig(config,p,cfgPath){if(!p||typeof p!=="object")return false;let changed=false;const set=(k,v)=>{if(JSON.stringify(v)!==JSON.stringify(config[k])){config[k]=v;changed=true;}};if(typeof p.product==="string"&&p.product.trim())set("product",p.product.trim());if(Array.isArray(p.leadFields)&&p.leadFields.length)set("leadFields",p.leadFields.map(s=>String(s).trim()).filter(Boolean));for(const k of ["contactEmail","persona","companyName","callbackNumber","callbackIn"])if(typeof p[k]==="string"&&p[k].trim())set(k,p[k].trim());if(Array.isArray(p.callList))set("callList",p.callList.map(n=>String(n).trim()).filter(Boolean));if(typeof p.searchEnabled==="boolean")set("searchEnabled",p.searchEnabled);if(typeof p.lang==="string"&&p.lang.trim()){const raw=p.lang.trim().toLowerCase();const lang=raw==="auto"?"auto":normalizeLanguage(raw,null);if(lang)set("lang",lang);}if(typeof p.voiceStyle==="string"&&/^(human|frank|friendly)$/.test(p.voiceStyle.trim()))set("voiceStyle",p.voiceStyle.trim());if(p.voip&&typeof p.voip==="object"&&p.voip.number&&p.voip.username){const prior=config.voip||{},provider=p.voip.provider||prior.provider||"",defaultServer=HOSTED_VOIP_SERVERS[provider]||HOSTED_VOIP_SERVERS[prior.provider]||"",next={provider,number:p.voip.number,extension:p.voip.extension||"",username:p.voip.username,sipPassword:p.voip.sipPassword||"",server:p.voip.server||prior.server||defaultServer,port:p.voip.port||prior.port||"",transport:p.voip.transport||prior.transport||"",ready:true};if(JSON.stringify(next)!==JSON.stringify(prior)){config.voip=next;changed=true;pushActivity(config,`VOIP line applied (${next.provider}, ${next.number}) - outbound calls use it.`);}}if(changed){saveConfig(config,cfgPath);pushActivity(config,"Admin updated the sales form from the portal - applied.");}return changed;}
function bumpStats(c,r){const day=new Date().toISOString().slice(0,10),s=c.stats||{since:day,day,calls:0,qualified:0,today:0,qualifiedToday:0,lastScore:0,bestScore:0,qualifiedRate:0};if(s.day!==day){s.day=day;s.today=0;s.qualifiedToday=0;}s.calls++;s.today++;if(r.goodLead){s.qualified++;s.qualifiedToday++;}s.lastScore=r.score;if(r.score>(s.bestScore||0))s.bestScore=r.score;s.qualifiedRate=Math.round((100*s.qualified)/Math.max(1,s.calls))/100;c.stats=s;return s;}
function pushActivity(c,msg){const f=(c.activity||[]).slice(0,29);f.unshift({at:new Date().toISOString(),msg});c.activity=f;return f;}
function post(url,body){return fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}).then(async r=>({status:r.status,body:await r.json().catch(()=>({}))}));}
function tryCockpit(configDir){if(!isPacked()||process.env.MAGICDIALER_COCKPIT!=="1")return;const cockpit=path.join(path.dirname(process.execPath),"cockpit.ps1");if(fs.existsSync(cockpit))try{spawn("powershell.exe",["-NoProfile","-Sta","-ExecutionPolicy","Bypass","-WindowStyle","Hidden","-File",cockpit],{stdio:"ignore"});}catch{}}
const AGENT_LOCK=path.join(os.homedir(),"AppData","Local","Magic Dialer","agent.lock");
function pidIsMagicDialer(pid){try{const out=execSync(`tasklist /FI "PID eq ${pid}" /FO CSV /NH`,{encoding:"utf8",stdio:["ignore","pipe","ignore"],windowsHide:true});return /(magicdialer|agent)\.exe/i.test(out);}catch{return false;}}
function takeAgentLock(){if(!isPacked())return true;try{if(fs.existsSync(AGENT_LOCK)){const old=Number(String(fs.readFileSync(AGENT_LOCK,"utf8")).trim());if(old&&pidAlive(old)&&pidIsMagicDialer(old))return false;}fs.mkdirSync(path.dirname(AGENT_LOCK),{recursive:true});fs.writeFileSync(AGENT_LOCK,String(process.pid));process.on("exit",()=>{try{fs.unlinkSync(AGENT_LOCK);}catch{}});return true;}catch{return true;}}
const {createInterface}=require("node:readline");function ask(q){return new Promise(resolve=>{const rl=createInterface({input:process.stdin,output:process.stdout});rl.question(q+" ",a=>{rl.close();resolve(a.trim());});});}
async function runAgent(opts={}){const cfgPath=opts.configPath||defaultConfigPath(),configDir=path.dirname(cfgPath);let config=loadConfig(cfgPath);if(!takeAgentLock()){log("Magic Dialer is already running - opening its dashboard...");if(!openDashboardExternal())openBrowser("http://127.0.0.1:48771/");setTimeout(()=>process.exit(0),800);return;}try{localDb.open(configDir);log("Local database ready.");}catch(e){log("Local DB init failed: "+e.message);}const useWebUi=opts.webui===true||isPacked()||opts.setup===true||opts.open===true;let uiServer=null,setupDoneResolve=null;const setupDone=new Promise(r=>{setupDoneResolve=r;});const ensureWebUi=async()=>{if(uiServer)return uiServer;uiServer=await startWebUi({readConfig:()=>loadConfig(cfgPath),writeConfig:c=>saveConfig(c,cfgPath),statusPath:path.join(configDir,"status.json"),onSetup:cfg=>{try{setupDoneResolve(cfg);}catch{}},onMode:mode=>{try{log(`dashboard mode -> ${mode}`);}catch{}},serviceName:"Magic Dialer"});try{writeDashboardUrl(uiServer.url);}catch{}log(`dashboard: ${uiServer.url}`);return uiServer;};let opened=false;const maybeOpen=url=>{if(!opened){opened=true;openBrowser(url);}};if(!config||!config.token||!config.portalUrl){config=config||{};config.machineId=config.machineId||crypto.randomUUID();config.lang=config.lang||"auto";config.voiceStyle=config.voiceStyle||"friendly";if(opts.portalUrl&&opts.token){config.portalUrl=opts.portalUrl;config.token=opts.token;saveConfig(config,cfgPath);}if(!config.token||!config.portalUrl){log("No config yet - setting up.");if(useWebUi){const srv=await ensureWebUi();maybeOpen(srv.url);config=await setupDone;}else{config.portalUrl=opts.portalUrl||(await ask("Magic Dialer portal URL (from your admin):"));config.token=opts.token||(await ask("Your Magic Dialer access token (from your admin):"));saveConfig(config,cfgPath);}}}if(useWebUi){const srv=await ensureWebUi();if(!opts.noBrowser&&(opts.setup===true||opts.open===true||isPacked()))maybeOpen(srv.url);}tryCockpit(configDir);const productLabel=config.product||"Magic Dialer customer";const ui=patch=>setUi(configDir,{version:VERSION,agent:(config.persona||"autumn").toLowerCase().includes("female")?"Autumn":"Atlas",company:config.companyName||"our team",product:productLabel,machineId:config.machineId,stats:config.stats||null,strategy:(config.learning?topStrategy(config.learning):null),callListCount:Array.isArray(config.callList)?config.callList.length:0,logs:(config.activity||[]).slice(0,12),...patch});ui({status:"STARTING",mode:config.mode||"on",line:"Starting Magic Dialer agent..."});const portal=(config.portalUrl||"").replace(/\/+$/,"");
if(opts.call===true){try{const result=await runLocalCall({config,number:opts.number,onLog:m=>{log(m);ui({line:m});},onMode:m=>ui({mode:m})});config.learning=result.learning;bumpStats(config,result);pushActivity(config,`Local-media call done - score ${result.score}, ${result.goodLead?"QUALIFIED LEAD":"no lead"}. Strategy: ${(result.strategies||[]).slice(0,3).join(", ")||"intro"}`);saveConfig(config,cfgPath);const finalLine=`Call result - score ${result.score}, ${result.goodLead?"QUALIFIED LEAD":"no lead"}.`;log(finalLine);ui({mode:config.mode||"on",line:finalLine});}catch(e){log("Voice call failed: "+e.message);ui({mode:config.mode||"on",line:"Voice call failed - retrying later."});}if(opts.callOnce===true)return;}
while(true){try{const res=await post(`${portal}/api/heartbeat`,{token:config.token,voipReady:!!(config.voip&&config.voip.ready),sync:sync.buildSyncPayload()});if(res.status===200&&res.body){if(res.body.disabled){log("DISABLED by admin - stopping work.");ui({status:"DISABLED",mode:"off",line:"Disabled by admin."});process.exit(0);}applyPortalConfig(config,res.body.config,cfgPath);if(res.body.sync)sync.processSyncResponse(res.body.sync);const stats=localDb.stats(),hl=`heartbeat OK | ${stats.leads} leads, ${stats.calls} calls, ${stats.leadsUnsynced} unsynced`;log(hl);ui({status:"ONLINE",mode:config.mode||"on",line:hl});}else ui({status:"OFFLINE",mode:config.mode||"on",line:"Heartbeat rejected - check your access key."});}catch(err){log(`heartbeat failed (${err.code||err.message}) - retrying. Agent continues offline.`);ui({status:"OFFLINE",mode:config.mode||"on",line:"Reconnecting to portal..."});}await new Promise(r=>setTimeout(r,HEARTBEAT_INTERVAL_MS));}}
module.exports={runAgent,loadConfig,saveConfig,defaultConfigPath,applyPortalConfig,bumpStats,pushActivity};
if(require.main===module){const argv=process.argv.slice(2),setup=argv.includes("--setup"),open=argv.includes("--open")||argv.includes("--launch")||argv.includes("--show"),call=argv.includes("--call")||argv.includes("--call-once"),callOnce=argv.includes("--call-once"),noBrowser=argv.includes("--no-browser")||argv.includes("--silent")||argv.includes("--startup"),rest=argv.filter(a=>!a.startsWith("--"));if(argv.includes("--watchdog")){runWatchdog(rest).catch(e=>{console.error(e);process.exit(1);});}else runAgent({token:rest[0],portalUrl:rest[1],setup,call,callOnce,open,noBrowser}).catch(e=>{console.error(e);process.exit(1);});}
