const assert=require("node:assert");const fs=require("node:fs");const os=require("node:os");const path=require("node:path");
const u=require("./auto-update");
assert.equal(u.newer("1.3.1","1.3.0"),true);assert.equal(u.newer("1.3.0","1.3.0"),false);assert.equal(u.newer("1.2.9","1.3.0"),false);
assert.ok(u.MANIFEST_URL.startsWith("https://"));
assert.equal(u.validManifest({version:"1.3.1",sha256:"a".repeat(64),url:u.RELEASE_PREFIX+"magic-dialer-engine-windows.exe"}),true);
assert.equal(u.validManifest({version:"1.3.1",sha256:"a".repeat(64),url:"https://evil.example/x.exe"}),false);
assert.equal(u.validManifest({version:"x",sha256:"a".repeat(64),url:u.RELEASE_PREFIX+"x.exe"}),false);
assert.equal(u.validManifest({version:"1.3.1",sha256:"bad",url:u.RELEASE_PREFIX+"x.exe"}),false);
const originalLocal=process.env.LOCALAPPDATA;const sd=fs.mkdtempSync(path.join(os.tmpdir(),"md-seed-"));process.env.LOCALAPPDATA=sd;const seedDir=u._test.stateDir();fs.mkdirSync(seedDir,{recursive:true});const seed=path.join(seedDir,"known-good-1.3.1.exe");fs.writeFileSync(seed,"seed");assert.equal(u._test.seededInstaller("1.3.1"),seed);assert.equal(u._test.seededInstaller("9.9.9"),null);process.env.LOCALAPPDATA=originalLocal;fs.rmSync(sd,{recursive:true,force:true});
const state={pendingVersion:"1.3.1",previousVersion:"1.3.0",lastGoodVersion:"1.3.0",lastGoodInstaller:"known-good.exe"}; assert.equal(state.lastGoodVersion,state.previousVersion); state.blockedVersion=state.pendingVersion; state.pendingVersion=null; assert.equal(state.blockedVersion,"1.3.1"); assert.equal(state.pendingVersion,null);
(async()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),"md-hash-"));const p=path.join(d,"x");fs.writeFileSync(p,"known-good");assert.equal(await u.sha256(p),"edb89d09b913b577efbd63f53446d060c97d339166531661a5196a0cf6b796bd");fs.rmSync(d,{recursive:true,force:true});console.log("auto-update behavior: PASS")})().catch(e=>{console.error(e);process.exit(1)});
